# Generated by Django 4.2.1 on 2023-06-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expalne_course',
            name='explane_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expalne_course',
            name='text_one',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_course',
            name='first_choose',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_course',
            name='quiz_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_course',
            name='second_choose',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quiz_course',
            name='third_choose',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='admin_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_private',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_private',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
