# Generated by Django 4.2.1 on 2023-06-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin_app', '0002_alter_class_class_name_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expalne_course',
            name='text_tow',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
